### ISSUE TITLE
c-\ can be mapped to directly

### ISSUE THREAD

**Issue by lenormf** [andreyorst/langmap.kak#2]
Hi,

The configuration example maps to a replacement character, which can be replaced with <kbd>c-\\</kbd> directly.

HTH.

**Comment by andreyorst** [comment]
>
> Hi,
>
> The configuration example maps to a replacement character, which can be
> replaced with c-\ directly.
>
> HTH.
>
Oh, that's great! When I wrote this example it was impossible IIRC.
